### PR TITLE
Added skip, restart buttons

### PR DESCRIPTION
**Pull request by kevindirkmunroe**
Skip - skip this step of ProgressSteps. Includes function hook onSkip() for custom skip behavior e.g. insert default data for this step.

Restart - rewind to 1st step of ProgressSteps. Includes function hook onRestart() for custom restart behavior, e.g. clear all collected data.

### CODE REVIEW

**Comment by colbymillerdev** [comment]
Hey @kevindirkmunroe -

Thanks for submitting this PR! I think it's a really great idea to have the functionality to skip steps and go back to the start. However, having this done with more buttons added to the bottom of the screen might make the UI/UX seem cluttered, especially on smaller screen sizes.

I think it'd be cleaner to make each step icon at the top clickable for skipping/moving to that step, which can also be disabled if the user desires.

Let me know your thoughts!

**Comment by kevindirkmunroe** [comment]
> Hey @kevindirkmunroe -
> 
> Thanks for submitting this PR! I think it's a really great idea to have the functionality to skip steps and go back to the start. However, having this done with more buttons added to the bottom of the screen might make the UI/UX seem cluttered, especially on smaller screen sizes.
> 
> I think it'd be cleaner to make each step icon at the top clickable for skipping/moving to that step, which can also be disabled if the user desires.
> 
> Let me know your thoughts!

I like the idea of removing 'Restart' button, and instead clicking the first step in the top display to restart. However, I'm leaning towards keeping the 'Skip' button since Skip enabled/disabled is a visual cue to whether the current step is skippable.

**Comment by colbymillerdev** [comment]
@kevindirkmunroe - Thought about this some more; All steps can currently be skipped by pressing the next button. The only way they can't be skipped is if the `errors` or `nextBtnDisabled` props are set to true on the `<ProgressStep />` component. So I think the intent of a skip button can be handled by current functionality.

**Comment by kevindirkmunroe** [comment]
stakeholders agree skip can be handled by next appearing active, restart via clicking first step in wizard flow. Closing.

**Pull request closed without merging**
